In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Age': [22, 25, 47, 52, 46, 56, 28, 33, 41, 60],
    'Income': [25000, 30000, 80000, 90000, 75000, 100000, 40000, 50000, 65000, 120000]
}

df = pd.DataFrame(data)
df

   Age  Income
0   22   25000
1   25   30000
2   47   80000
3   52   90000
4   46   75000
5   56  100000
6   28   40000
7   33   50000
8   41   65000
9   60  120000

In [3]:
bins = [20, 30, 40, 50, 60, 70]
labels = ['20-30', '30-40', '40-50', '50-60', '60-70']

df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels)
df

   Age  Income AgeGroup
0   22   25000    20-30
1   25   30000    20-30
2   47   80000    40-50
3   52   90000    50-60
4   46   75000    40-50
5   56  100000    50-60
6   28   40000    20-30
7   33   50000    30-40
8   41   65000    40-50
9   60  120000    50-60

In [4]:
grouped_stats = df.groupby('AgeGroup')['Income'].agg(['mean', 'median', 'min', 'max', 'std'])
grouped_stats

                   mean    median    min     max           std
AgeGroup
20-30      31666.666667   30000.0  25000   40000   7637.626158
30-40      50000.000000   50000.0  50000   50000           NaN
40-50      73333.333333   75000.0  65000   80000   7637.626158
50-60     103333.333333  100000.0  90000  120000  15275.252317

In [5]:
income_list = df.groupby('AgeGroup')['Income'].apply(list)
income_list

AgeGroup
20-30      [25000, 30000, 40000]
30-40                    [50000]
40-50      [80000, 75000, 65000]
50-60    [90000, 100000, 120000]
Name: Income, dtype: object

In [6]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'

col_name = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris = pd.read_csv(url, names=col_name)

iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [7]:
print("Shape:", iris.shape)
print("\nInfo:\n")
iris.info()

Shape: (150, 5)

Info:

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   class         150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [8]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
iris_grouped = iris.groupby('class').describe()
iris_grouped

                sepal_length                                              \
                       count   mean       std  min    25%  50%  75%  max
class
Iris-setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

                sepal_width         ... petal_length      petal_width         \
                      count   mean  ...          75%  max       count   mean
class                               ...
Iris-setosa            50.0  3.418  ...        1.575  1.9        50.0  0.244
Iris-versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
Iris-virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                      std  min  25%  50%  75%  max
class
Iris-setosa      0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [10]:
iris.groupby('class').agg(['mean', 'std', 'min', 'max'])

                sepal_length                     sepal_width                 \
                        mean       std  min  max        mean       std  min
class
Iris-setosa            5.006  0.352490  4.3  5.8       3.418  0.381024  2.3
Iris-versicolor        5.936  0.516171  4.9  7.0       2.770  0.313798  2.0
Iris-virginica         6.588  0.635880  4.9  7.9       2.974  0.322497  2.2

                     petal_length                     petal_width            \
                 max         mean       std  min  max        mean       std
class
Iris-setosa      4.4        1.464  0.173511  1.0  1.9       0.244  0.107210
Iris-versicolor  3.4        4.260  0.469911  3.0  5.1       1.326  0.197753
Iris-virginica   3.8        5.552  0.551895  4.5  6.9       2.026  0.274650


                 min  max
class
Iris-setosa      0.1  0.6
Iris-versicolor  1.0  1.8
Iris-virginica   1.4  2.5

In [11]:
setosa = iris[iris['class'] == 'Iris-setosa']

print("Setosa Statistics:\n")
print(setosa.describe())

Setosa Statistics:

       sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        5.00600     3.418000      1.464000      0.24400
std         0.35249     0.381024      0.173511      0.10721
min         4.30000     2.300000      1.000000      0.10000
25%         4.80000     3.125000      1.400000      0.20000
50%         5.00000     3.400000      1.500000      0.20000
75%         5.20000     3.675000      1.575000      0.30000
max         5.80000     4.400000      1.900000      0.60000

In [12]:
iris.groupby('class')['sepal_length'].quantile([0.25, 0.5, 0.75])

class
Iris-setosa      0.25    4.800
                 0.50    5.000
                 0.75    5.200
Iris-versicolor  0.25    5.600
                 0.50    5.900
                 0.75    6.300
Iris-virginica   0.25    6.225
                 0.50    6.500
                 0.75    6.900
Name: sepal_length, dtype: float64